### ISSUE TITLE
ZECWallet Lightwalletd Report

### ISSUE THREAD

**Issue by braddmiller** [zcash-hackworks/lightwalletd#137]
Create a basic changelog of the macro changes (removing sql, new RPCs, etc.) detailing the change and why it was necessary or preferable. The idea is the be able to split these up into PRs for code review later after justifying it's a change we want to make.

**Comment by LarryRuane** [comment]
[WIP] (Still working on this) Check the ones we want to merge:
- [ ] add RPC `GetLightdInfo` to frontend `service.go`
- [ ] add RPC `GetUtxos` to frontend `service.go` (insight explorer rpc)
- [ ] replaced sqlite with in-memory block cache and option to set #blocks (default 40k)
- [ ] query zcashd for sapling height (instead of hard-code, works with mainnet, testnet)
