### ISSUE TITLE
Fix test stack

### ISSUE THREAD

**Issue by mdr0id** [zcash-hackworks/lightwalletd#42]
``` got test -run '' ```

```
lightwalletd git:(testing-fixes) ✗ go test -run ''                                   
can't load package: package github.com/zcash-hackworks/lightwalletd: unknown import path "github.com/zcash-hackworks/lightwalletd": cannot find module providing package github.com/zcash-hackworks/lightwalletd
```

**Comment by LarryRuane** [comment]
It appears that it's necessary to change-directory to where each `*_test.go` file is located:
```
$ cd lightwalletd/parser
$ go test
PASS
ok  	github.com/zcash-hackworks/lightwalletd/parser	0.012s
$ 
```
There are three test files in this directory; the above ran all three of them. (I'm sure of that because I purposely broke each of them one at a time, and `go test` failed each time.)

It might be a good idea to add a super-trivial `Makefile` to the top level directory with a `test` target that would `cd` to each directory that contains tests and runs `go test` there. The default target could similarly run `go build` (as is conventional with makefiles). I'll make a PR for that now. I know having makefiles in Go projects is slightly unusual, but I've seen it before (somewhere that I can't recall), and if it's really trivial makefile, I don't think anyone will mind.

**Comment by mdr0id** [comment]
This has been discussed and closing
